### ISSUE TITLE
Not working on sf 3.3

### ISSUE THREAD

**Issue by mvrhov** [mariusbalcytis/webpack-bundle#48]
running `app/console maba:webpack:dev-server` returns 
`sh: 1: exec: exec: not found`

Changing prefix to '' fixes the issue
https://github.com/mariusbalcytis/webpack-bundle/blob/master/src/Compiler/WebpackCompiler.php#L96

**Comment by mariusbalcytis** [comment]
What operating system are you using?

**Comment by mvrhov** [comment]
ubuntu 16.04

**Comment by mvrhov** [comment]
Hm. Still same os still sf 3.3.

This is the var_dump

```
webpack-bundle/src/Compiler/WebpackProcessBuilder.php:91:
string(246) "exec 'node_modules/.bin/webpack-dashboard' -- exec 'node_modules/.bin/webpack-dev-server' '--config' '/srv/www/kartoncek/kartoncek/site/app/var/cache/dev/webpack.config.js' '--hot' '--history-api-fallback' '--inline' '--colors' '--host' '0.0.0.0'"
Error: spawn exec ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
internal/process.js:155
      throw new TypeError('invalid pid');
      ^

TypeError: invalid pid
    at process.kill (internal/process.js:155:13)
    at process.<anonymous> (/srv/www/kartoncek/kartoncek/site/node_modules/webpack-dashboard/bin/webpack-dashboard.js:79:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:146:15)
    at Immediate.<anonymous> (/srv/www/kartoncek/kartoncek/site/node_modules/blessed/lib/widgets/screen.js:221:15)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```
